exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('spendings').del()
    .then(function () {
      // Inserts seed entries
      return knex('spendings').insert([
        {"date":"2015-01-01","month":"Jan","item":"P.G.E. Webpay Elec","amount":62.93,"category":"Utilities","memo":""},
{"date":"2015-01-05","month":"Jan","item":"AT&T*BILL PAYMENT, TX","amount":43.91,"category":"Utilities","memo":""},
{"date":"2015-01-10","month":"Jan","item":"SAFEWAY STORE, AZ","amount":8.64,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-01-16","month":"Jan","item":"FRYS FUEL, AZ","amount":17.41,"category":"Gas stations","memo":""},
{"date":"2015-01-17","month":"Jan","item":"SAFEWAY STORE, AZ","amount":9.98,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-01-17","month":"Jan","item":"COSTCO WHOLESALE PHOENIX AZ","amount":48.33,"category":"Grocery stores","memo":""},
{"date":"2015-01-19","month":"Jan","item":"AT&T*BILL PAYMENT, TX","amount":65,"category":"Utilities","memo":""},
{"date":"2015-01-19","month":"Jan","item":"STARBUCKS, AZ","amount":8.7,"category":"Restaurants","memo":"Over price…"},
{"date":"2015-01-19","month":"Jan","item":"COSTCO WHOLESALE PHOENIX AZ","amount":4.89,"category":"Grocery stores","memo":""},
{"date":"2015-01-20","month":"Jan","item":"CHIPOTLE, AZ","amount":19.5,"category":"Restaurants","memo":"Bought lunch for friends"},
{"date":"2015-01-24","month":"Jan","item":"STARBUCKS, AZ","amount":8.5,"category":"Restaurants","memo":""},
{"date":"2015-01-27","month":"Jan","item":"SAFEWAY STORE, AZ","amount":5.95,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-01-27","month":"Jan","item":"FRYS FUEL, AZ","amount":13.39,"category":"Gas stations","memo":""},
{"date":"2015-01-29","month":"Jan","item":"ALBERTSONS, AZ","amount":1.58,"category":"Grocery stores","memo":""},
{"date":"2015-01-29","month":"Jan","item":"FRYS FUEL, AZ","amount":14.79,"category":"Gas stations","memo":""},
{"date":"2015-01-30","month":"Jan","item":"MCDONALD'S, OR","amount":4,"category":"Restaurants","memo":""},
{"date":"2015-01-30","month":"Jan","item":"STARBUCKS, AZ","amount":5.55,"category":"Restaurants","memo":""},
{"date":"2015-01-31","month":"Jan","item":"CIRCLE K, AZ","amount":25.56,"category":"Gas stations","memo":""},
{"date":"2015-02-01","month":"Feb","item":"FRYS-FOOD-DRG, AZ","amount":45.15,"category":"Grocery stores","memo":"I save $10, Yes!!"},
{"date":"2015-02-01","month":"Feb","item":"COSTCO WHOLESALE PHOENIX AZ","amount":27.27,"category":"Grocery stores","memo":""},
{"date":"2015-02-02","month":"Feb","item":"CHOMPIES RESTAURANT DELI, AZ","amount":21.09,"category":"Restaurants","memo":""},
{"date":"2015-02-03","month":"Feb","item":"SAFEWAY STORE, AZ","amount":22.55,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-02-04","month":"Feb","item":"FRYS FUEL, AZ","amount":19.13,"category":"Gas stations","memo":""},
{"date":"2015-02-05","month":"Feb","item":"AT&T*BILL PAYMENT, TX","amount":166.99,"category":"Utilities","memo":"Include the abroad package"},
{"date":"2015-02-07","month":"Feb","item":"P.G.E. Webpay Elec","amount":53.33,"category":"Utilities","memo":""},
{"date":"2015-02-07","month":"Feb","item":"STARBUCKS, AZ","amount":7.78,"category":"Restaurants","memo":""},
{"date":"2015-02-07","month":"Feb","item":"COSTCO WHOLESALE PHOENIX AZ","amount":98.99,"category":"Grocery stores","memo":""},
{"date":"2015-02-08","month":"Feb","item":"STARBUCKS, AZ","amount":4.49,"category":"Restaurants","memo":""},
{"date":"2015-02-08","month":"Feb","item":"STARBUCKS, AZ","amount":8.21,"category":"Restaurants","memo":""},
{"date":"2015-02-12","month":"Feb","item":"ALBERTSONS, AZ","amount":4.29,"category":"Grocery stores","memo":""},
{"date":"2015-02-12","month":"Feb","item":"FRYS-FOOD-DRG, AZ","amount":105.54,"category":"Grocery stores","memo":""},
{"date":"2015-02-14","month":"Feb","item":"CHOMPIES RESTAURANT DELI, AZ","amount":53.42,"category":"Restaurants","memo":"Took Grandma for a dinner.  She refilled iced tea 10 times"},
{"date":"2015-02-15","month":"Feb","item":"SAFEWAY STORE, AZ","amount":3.8,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-02-15","month":"Feb","item":"SAFEWAY STORE, AZ","amount":2.16,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-02-15","month":"Feb","item":"STARBUCKS, AZ","amount":8.12,"category":"Restaurants","memo":""},
{"date":"2015-02-16","month":"Feb","item":"CHICK-FIL-A, AZ","amount":14.92,"category":"Restaurants","memo":""},
{"date":"2015-02-16","month":"Feb","item":"STARBUCKS, AZ","amount":7.91,"category":"Restaurants","memo":""},
{"date":"2015-02-16","month":"Feb","item":"CHIPOTLE, AZ","amount":6.7,"category":"Restaurants","memo":""},
{"date":"2015-02-19","month":"Feb","item":"FRYS FUEL, AZ","amount":19.67,"category":"Gas stations","memo":""},
{"date":"2015-02-21","month":"Feb","item":"FRYS-FOOD-DRG, AZ","amount":7.07,"category":"Grocery stores","memo":""},
{"date":"2015-02-21","month":"Feb","item":"FRYS-FOOD-DRG, AZ","amount":73.19,"category":"Grocery stores","memo":""},
{"date":"2015-02-28","month":"Feb","item":"MCMENAMINS PUB, OR","amount":21.05,"category":"Restaurants","memo":"Last day in Oregon and last meal. I'll never forget this place"},
{"date":"2015-02-28","month":"Feb","item":"PITA JUNGLE - DR, AZ","amount":18.73,"category":"Restaurants","memo":""},
{"date":"2015-02-28","month":"Feb","item":"COSTCO WHOLESALE PHOENIX AZ","amount":63.12,"category":"Grocery stores","memo":""},
{"date":"2015-03-01","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":10.81,"category":"Grocery stores","memo":""},
{"date":"2015-03-01","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":31.84,"category":"Grocery stores","memo":""},
{"date":"2015-03-03","month":"Mar","item":"SAFEWAY STORE, AZ","amount":13.12,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-03-05","month":"Mar","item":"AT&T*BILL PAYMENT, TX","amount":168.63,"category":"Utilities","memo":"Include the abroad package"},
{"date":"2015-03-07","month":"Mar","item":"P.G.E. Webpay Elec","amount":8.42,"category":"Utilities","memo":""},
{"date":"2015-03-08","month":"Mar","item":"BEST BUY, OR","amount":12.49,"category":"Electronics & software","memo":""},
{"date":"2015-03-08","month":"Mar","item":"SHIGEZO JAPANESE RESPORTLAND OR","amount":31.5,"category":"Restaurants","memo":""},
{"date":"2015-03-13","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":97.22,"category":"Grocery stores","memo":""},
{"date":"2015-03-13","month":"Mar","item":"COSTCO WHOLESALE PHOENIX AZ","amount":70.09,"category":"Grocery stores","memo":""},
{"date":"2015-03-14","month":"Mar","item":"STARBUCKS, AZ","amount":3.35,"category":"Restaurants","memo":""},
{"date":"2015-03-16","month":"Mar","item":"MCDONALD'S, OR","amount":6.7,"category":"Restaurants","memo":""},
{"date":"2015-03-16","month":"Mar","item":"CLAIM JUMPER, PHOENIX AZ","amount":113.27,"category":"Restaurants","memo":"Dinner with mother in law.  I was nervous"},
{"date":"2015-03-17","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":46.54,"category":"Grocery stores","memo":""},
{"date":"2015-03-17","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":15.21,"category":"Grocery stores","memo":""},
{"date":"2015-03-17","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":7.24,"category":"Grocery stores","memo":""},
{"date":"2015-03-18","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":1.54,"category":"Grocery stores","memo":""},
{"date":"2015-03-18","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":4.29,"category":"Grocery stores","memo":""},
{"date":"2015-03-18","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":6.49,"category":"Grocery stores","memo":""},
{"date":"2015-03-18","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":5.4,"category":"Grocery stores","memo":""},
{"date":"2015-03-18","month":"Mar","item":"ASIANA MARKET, AZ","amount":47.52,"category":"Grocery stores","memo":""},
{"date":"2015-03-18","month":"Mar","item":"AT&T*BILL PAYMENT, TX","amount":27.08,"category":"Utilities","memo":""},
{"date":"2015-03-20","month":"Mar","item":"COSTCO WHOLESALE PHOENIX AZ","amount":413.86,"category":"Grocery stores","memo":""},
{"date":"2015-03-20","month":"Mar","item":"COSTCO WHOLESALE PHOENIX AZ","amount":541.49,"category":"Grocery stores","memo":"Bought TV for living room"},
{"date":"2015-03-22","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":1.26,"category":"Grocery stores","memo":""},
{"date":"2015-03-22","month":"Mar","item":"STARBUCKS, AZ","amount":10.18,"category":"Restaurants","memo":"Over price!!!"},
{"date":"2015-03-22","month":"Mar","item":"COSTCO WHOLESALE PHOENIX AZ","amount":45.99,"category":"Grocery stores","memo":""},
{"date":"2015-03-24","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":7.36,"category":"Grocery stores","memo":""},
{"date":"2015-03-25","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":12.56,"category":"Grocery stores","memo":""},
{"date":"2015-03-25","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":8.11,"category":"Grocery stores","memo":""},
{"date":"2015-03-27","month":"Mar","item":"FRYS-FOOD-DRG, AZ","amount":102.62,"category":"Grocery stores","memo":"I bought too much today, I confess my sin."},
{"date":"2015-03-27","month":"Mar","item":"PAPA MURPHY'S, AZ","amount":30,"category":"Restaurants","memo":""},
{"date":"2015-03-28","month":"Mar","item":"CIRCLE K, AZ","amount":6.9,"category":"Gas stations","memo":""},
{"date":"2015-03-29","month":"Mar","item":"APPLEBEES, AZ","amount":37.37,"category":"Restaurants","memo":"Steak was dried… like mom's steak"},
{"date":"2015-04-29","month":"Apr","item":"APPLE STORE, AZ","amount":604.57,"category":"Electronics & software","memo":"I was so drunk, I don't remember when I bought this……"},
{"date":"2015-04-08","month":"Apr","item":"PANDA EXPRESS, AZ","amount":9.92,"category":"Restaurants","memo":""},
{"date":"2015-04-08","month":"Apr","item":"CHOMPIES RESTAURANT DELI, AZ","amount":25.09,"category":"Restaurants","memo":"Brunch with my spouse"},
{"date":"2015-04-09","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":3.25,"category":"Grocery stores","memo":""},
{"date":"2015-04-09","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":252.27,"category":"Grocery stores","memo":"Bought gift cards for Grandma"},
{"date":"2015-04-09","month":"Apr","item":"COSTCO GAS PHOENIX AZ","amount":21.65,"category":"Gas stations","memo":""},
{"date":"2015-04-10","month":"Apr","item":"City Phx Water Payment PPD","amount":85.65,"category":"Utilities","memo":""},
{"date":"2015-04-10","month":"Apr","item":"SPROUTS FARMERS, AZ","amount":1.99,"category":"Grocery stores","memo":"Wanted to use Android payment"},
{"date":"2015-04-11","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":3.22,"category":"Grocery stores","memo":""},
{"date":"2015-04-11","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":14.46,"category":"Grocery stores","memo":""},
{"date":"2015-04-12","month":"Apr","item":"SAFEWAY STORE, AZ","amount":5.88,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-04-13","month":"Apr","item":"HODORI RESTAURANT, AZ","amount":15.62,"category":"Restaurants","memo":""},
{"date":"2015-04-13","month":"Apr","item":"FRYS FUEL, AZ","amount":17.93,"category":"Gas stations","memo":""},
{"date":"2015-04-14","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":9.58,"category":"Grocery stores","memo":""},
{"date":"2015-04-14","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":2.71,"category":"Grocery stores","memo":""},
{"date":"2015-04-14","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":60.37,"category":"Grocery stores","memo":""},
{"date":"2015-04-15","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":1.49,"category":"Grocery stores","memo":""},
{"date":"2015-04-16","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":3.49,"category":"Grocery stores","memo":""},
{"date":"2015-04-16","month":"Apr","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-04-17","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":5.49,"category":"Grocery stores","memo":""},
{"date":"2015-04-17","month":"Apr","item":"BEST BUY, OR","amount":23.81,"category":"Electronics & software","memo":"Apple USB cable, over price"},
{"date":"2015-04-17","month":"Apr","item":"COX*PHOENIX COMM SERV, AZ","amount":49.99,"category":"Utilities","memo":""},
{"date":"2015-04-17","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-04-17","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":53.5,"category":"Grocery stores","memo":""},
{"date":"2015-04-18","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":51.38,"category":"Grocery stores","memo":""},
{"date":"2015-04-18","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.08,"category":"Grocery stores","memo":""},
{"date":"2015-04-18","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":26.45,"category":"Grocery stores","memo":""},
{"date":"2015-04-19","month":"Apr","item":"MEKONG SUPERMARKET, AZ","amount":37.89,"category":"Grocery stores","memo":""},
{"date":"2015-04-20","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":27.05,"category":"Grocery stores","memo":""},
{"date":"2015-04-21","month":"Apr","item":"SAFEWAY STORE, AZ","amount":2.79,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-04-21","month":"Apr","item":"BEST BUY, OR","amount":75.8,"category":"Electronics & software","memo":""},
{"date":"2015-04-23","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":13.02,"category":"Grocery stores","memo":""},
{"date":"2015-04-24","month":"Apr","item":"SAFEWAY STORE, AZ","amount":3.99,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-04-24","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":19.36,"category":"Grocery stores","memo":""},
{"date":"2015-04-25","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":9.8,"category":"Grocery stores","memo":""},
{"date":"2015-04-25","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":33.93,"category":"Grocery stores","memo":""},
{"date":"2015-04-25","month":"Apr","item":"THE GELATO SPOT, AZ","amount":14.64,"category":"Restaurants","memo":"This place is my new favorite"},
{"date":"2015-04-26","month":"Apr","item":"SAFEWAY STORE, AZ","amount":6.98,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-04-26","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":5.14,"category":"Grocery stores","memo":""},
{"date":"2015-04-27","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":29.98,"category":"Grocery stores","memo":""},
{"date":"2015-04-28","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":7.75,"category":"Grocery stores","memo":""},
{"date":"2015-04-29","month":"Apr","item":"MEKONG SUPERMARKET, AZ","amount":36.97,"category":"Grocery stores","memo":""},
{"date":"2015-04-30","month":"Apr","item":"FRYS-FOOD-DRG, AZ","amount":10.3,"category":"Grocery stores","memo":""},
{"date":"2015-04-30","month":"Apr","item":"COSTCO WHOLESALE PHOENIX AZ","amount":30.74,"category":"Grocery stores","memo":""},
{"date":"2015-05-01","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-03","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-06","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-08","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-01","month":"May","item":"DAIRY QUEEN, AZ","amount":8.58,"category":"Restaurants","memo":""},
{"date":"2015-05-01","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.57,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-02","month":"May","item":"SAFEWAY STORE, AZ","amount":5.78,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-05-03","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":5.19,"category":"Grocery stores","memo":""},
{"date":"2015-05-03","month":"May","item":"CIRCLE K, AZ","amount":2.74,"category":"Gas stations","memo":""},
{"date":"2015-05-03","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":31.82,"category":"Grocery stores","memo":""},
{"date":"2015-05-05","month":"May","item":"City Phx Water Payment PPD","amount":89.91,"category":"Utilities","memo":""},
{"date":"2015-05-05","month":"May","item":"AT&T*BILL PAYMENT, TX","amount":60.63,"category":"Utilities","memo":""},
{"date":"2015-05-06","month":"May","item":"ALBERTSONS, AZ","amount":6.18,"category":"Grocery stores","memo":""},
{"date":"2015-05-06","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-08","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":52.46,"category":"Grocery stores","memo":""},
{"date":"2015-05-08","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":6.29,"category":"Grocery stores","memo":""},
{"date":"2015-05-08","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-08","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":61.01,"category":"Grocery stores","memo":""},
{"date":"2015-05-11","month":"May","item":"PARADISE BAKERY & CAFE, AZ","amount":7.1,"category":"Restaurants","memo":""},
{"date":"2015-05-11","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.57,"category":"Grocery stores","memo":""},
{"date":"2015-05-11","month":"May","item":"COSTCO GAS PHOENIX AZ","amount":25.57,"category":"Gas stations","memo":""},
{"date":"2015-05-12","month":"May","item":"FRYS FUEL, AZ","amount":23.28,"category":"Gas stations","memo":""},
{"date":"2015-05-13","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":13.57,"category":"Grocery stores","memo":""},
{"date":"2015-05-13","month":"May","item":"COX*PHOENIX COMM SERV, AZ","amount":115.98,"category":"Utilities","memo":""},
{"date":"2015-05-13","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":43.17,"category":"Grocery stores","memo":""},
{"date":"2015-05-14","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":4.24,"category":"Grocery stores","memo":""},
{"date":"2015-05-15","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":93.41,"category":"Grocery stores","memo":""},
{"date":"2015-05-15","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":5.14,"category":"Grocery stores","memo":""},
{"date":"2015-05-16","month":"May","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-05-18","month":"May","item":"CHICK-FIL-A, AZ","amount":15.49,"category":"Restaurants","memo":""},
{"date":"2015-05-18","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":22.31,"category":"Grocery stores","memo":""},
{"date":"2015-05-21","month":"May","item":"SAFEWAY STORE, AZ","amount":4.33,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-05-21","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":6.43,"category":"Grocery stores","memo":""},
{"date":"2015-05-22","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":89.38,"category":"Grocery stores","memo":""},
{"date":"2015-05-22","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-22","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":30,"category":"Grocery stores","memo":""},
{"date":"2015-05-24","month":"May","item":"SAFEWAY STORE, AZ","amount":1.99,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-05-24","month":"May","item":"SAFEWAY STORE, AZ","amount":8.12,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-05-24","month":"May","item":"MEKONG SUPERMARKET, AZ","amount":16.76,"category":"Grocery stores","memo":""},
{"date":"2015-05-24","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":6.58,"category":"Grocery stores","memo":""},
{"date":"2015-05-25","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":12.18,"category":"Grocery stores","memo":""},
{"date":"2015-05-26","month":"May","item":"PAPA MURPHY'S, AZ","amount":10,"category":"Restaurants","memo":""},
{"date":"2015-05-27","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-05-28","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":1.49,"category":"Grocery stores","memo":""},
{"date":"2015-05-28","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":2.65,"category":"Grocery stores","memo":""},
{"date":"2015-05-28","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":17.32,"category":"Grocery stores","memo":""},
{"date":"2015-05-28","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":28.05,"category":"Grocery stores","memo":""},
{"date":"2015-05-29","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":5.28,"category":"Grocery stores","memo":""},
{"date":"2015-05-29","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":2.79,"category":"Grocery stores","memo":""},
{"date":"2015-05-30","month":"May","item":"MEKONG SUPERMARKET, AZ","amount":51.69,"category":"Grocery stores","memo":"Bought a bag of rice"},
{"date":"2015-05-30","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":13.85,"category":"Grocery stores","memo":""},
{"date":"2015-05-30","month":"May","item":"FRYS-FOOD-DRG, AZ","amount":7.19,"category":"Grocery stores","memo":""},
{"date":"2015-05-30","month":"May","item":"CIRCLE K, AZ","amount":18.81,"category":"Gas stations","memo":""},
{"date":"2015-05-30","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.57,"category":"Grocery stores","memo":""},
{"date":"2015-05-30","month":"May","item":"COSTCO WHOLESALE PHOENIX AZ","amount":102.27,"category":"Grocery stores","memo":""},
{"date":"2015-06-01","month":"Jun","item":"SAFEWAY STORE, AZ","amount":39.69,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-06-01","month":"Jun","item":"MCDONALD'S, OR","amount":4.31,"category":"Restaurants","memo":""},
{"date":"2015-06-02","month":"Jun","item":"CIRCLE K, AZ","amount":31.46,"category":"Gas stations","memo":""},
{"date":"2015-06-03","month":"Jun","item":"SAFEWAY STORE, AZ","amount":7.5,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-06-03","month":"Jun","item":"FRYS-FOOD-DRG, AZ","amount":3.29,"category":"Grocery stores","memo":""},
{"date":"2015-06-03","month":"Jun","item":"COX*PHOENIX COMM SERV, AZ","amount":115.98,"category":"Utilities","memo":""},
{"date":"2015-06-03","month":"Jun","item":"CHELSEA'S KITCHEN, AZ","amount":42.74,"category":"Restaurants","memo":"Burger cost $20…. Seriously??"},
{"date":"2015-06-05","month":"Jun","item":"FRYS-FOOD-DRG, AZ","amount":3.21,"category":"Grocery stores","memo":""},
{"date":"2015-06-05","month":"Jun","item":"AT&T*BILL PAYMENT, TX","amount":131.42,"category":"Utilities","memo":""},
{"date":"2015-06-06","month":"Jun","item":"CHERRYBLOSSOM NOODLE CAFE, AZ","amount":12.67,"category":"Restaurants","memo":"Japanese restaurant in Phoenix, it was good"},
{"date":"2015-06-07","month":"Jun","item":"SAFEWAY STORE, AZ","amount":5.56,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-06-07","month":"Jun","item":"SAFEWAY STORE, AZ","amount":5.4,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-06-07","month":"Jun","item":"SAFEWAY STORE, AZ","amount":30.83,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-06-07","month":"Jun","item":"DUNKIN, AZ","amount":3.45,"category":"Restaurants","memo":""},
{"date":"2015-06-08","month":"Jun","item":"DAIRY QUEEN, AZ","amount":6.68,"category":"Restaurants","memo":""},
{"date":"2015-06-10","month":"Jun","item":"DAIRY QUEEN, AZ","amount":7.12,"category":"Restaurants","memo":""},
{"date":"2015-06-12","month":"Jun","item":"FRYS-FOOD-DRG, AZ","amount":95.39,"category":"Grocery stores","memo":""},
{"date":"2015-06-14","month":"Jun","item":"City Phx Water Payment PPD","amount":77.63,"category":"Utilities","memo":""},
{"date":"2015-06-14","month":"Jun","item":"DUNKIN, AZ","amount":2.14,"category":"Restaurants","memo":""},
{"date":"2015-06-14","month":"Jun","item":"COSTCO WHOLESALE PHOENIX AZ","amount":54.14,"category":"Grocery stores","memo":""},
{"date":"2015-06-15","month":"Jun","item":"COSTCO WHOLESALE PHOENIX AZ","amount":5.99,"category":"Grocery stores","memo":""},
{"date":"2015-06-16","month":"Jun","item":"FRYS-FOOD-DRG, AZ","amount":12.16,"category":"Grocery stores","memo":""},
{"date":"2015-06-16","month":"Jun","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-06-17","month":"Jun","item":"FRYS-FOOD-DRG, AZ","amount":200,"category":"Grocery stores","memo":""},
{"date":"2015-07-02","month":"Jul","item":"COSTCO GAS PHOENIX AZ","amount":30.67,"category":"Gas stations","memo":""},
{"date":"2015-07-04","month":"Jul","item":"COSTCO GAS PHOENIX AZ","amount":25.69,"category":"Gas stations","memo":""},
{"date":"2015-07-05","month":"Jul","item":"AT&T*BILL PAYMENT, TX","amount":128.68,"category":"Utilities","memo":""},
{"date":"2015-07-12","month":"Jul","item":"STARBUCKS, AZ","amount":9.42,"category":"Restaurants","memo":""},
{"date":"2015-07-12","month":"Jul","item":"STARBUCKS, AZ","amount":7.39,"category":"Restaurants","memo":""},
{"date":"2015-07-13","month":"Jul","item":"City Phx Water Payment PPD","amount":62.94,"category":"Utilities","memo":""},
{"date":"2015-07-16","month":"Jul","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-07-17","month":"Jul","item":"FRYS FUEL, AZ","amount":30.97,"category":"Gas stations","memo":""},
{"date":"2015-07-23","month":"Jul","item":"FRYS FUEL, AZ","amount":31,"category":"Gas stations","memo":""},
{"date":"2015-07-28","month":"Jul","item":"PAPA MURPHY'S, AZ","amount":24,"category":"Restaurants","memo":""},
{"date":"2015-07-30","month":"Jul","item":"CHICK-FIL-A, AZ","amount":12.23,"category":"Restaurants","memo":""},
{"date":"2015-07-31","month":"Jul","item":"FRYS-FOOD-DRG, AZ","amount":7.63,"category":"Grocery stores","memo":""},
{"date":"2015-08-01","month":"Aug","item":"AT&T*BILL PAYMENT, TX","amount":363.86,"category":"Utilities","memo":"Purchased a new phone. $200 more than usual"},
{"date":"2015-08-01","month":"Aug","item":"DAIRY QUEEN, AZ","amount":9.27,"category":"Restaurants","memo":""},
{"date":"2015-08-01","month":"Aug","item":"COSTCO WHOLESALE PHOENIX AZ","amount":119.13,"category":"Grocery stores","memo":""},
{"date":"2015-08-02","month":"Aug","item":"FRYS FUEL, AZ","amount":33.3,"category":"Gas stations","memo":""},
{"date":"2015-08-04","month":"Aug","item":"COSTCO GAS PHOENIX AZ","amount":21.22,"category":"Gas stations","memo":""},
{"date":"2015-08-06","month":"Aug","item":"City Phx Water Payment PPD","amount":131.53,"category":"Utilities","memo":""},
{"date":"2015-08-06","month":"Aug","item":"FRYS-FOOD-DRG, AZ","amount":4.77,"category":"Grocery stores","memo":""},
{"date":"2015-08-07","month":"Aug","item":"COSTCO GAS PHOENIX AZ","amount":31.41,"category":"Gas stations","memo":""},
{"date":"2015-08-09","month":"Aug","item":"FRYS-FOOD-DRG, AZ","amount":8.49,"category":"Grocery stores","memo":""},
{"date":"2015-08-16","month":"Aug","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-08-25","month":"Aug","item":"FRYS-FOOD-DRG, AZ","amount":10,"category":"Grocery stores","memo":""},
{"date":"2015-08-28","month":"Aug","item":"COSTCO WHOLESALE PHOENIX AZ","amount":200.68,"category":"Grocery stores","memo":""},
{"date":"2015-09-01","month":"Sep","item":"AT&T*BILL PAYMENT, TX","amount":128.63,"category":"Utilities","memo":""},
{"date":"2015-09-03","month":"Sep","item":"COX*PHOENIX COMM SERV, AZ","amount":33.99,"category":"Utilities","memo":""},
{"date":"2015-09-06","month":"Sep","item":"City Phx Water Payment PPD","amount":117.94,"category":"Utilities","memo":""},
{"date":"2015-09-07","month":"Sep","item":"FRYS FUEL, AZ","amount":31.56,"category":"Gas stations","memo":""},
{"date":"2015-09-08","month":"Sep","item":"COSTCO GAS PHOENIX AZ","amount":24.73,"category":"Gas stations","memo":""},
{"date":"2015-09-09","month":"Sep","item":"MCDONALD'S, OR","amount":4,"category":"Restaurants","memo":""},
{"date":"2015-09-11","month":"Sep","item":"CIRCLE K, AZ","amount":1.61,"category":"Gas stations","memo":""},
{"date":"2015-09-13","month":"Sep","item":"FRYS-FOOD-DRG, AZ","amount":2.29,"category":"Grocery stores","memo":""},
{"date":"2015-09-13","month":"Sep","item":"MCDONALD'S, OR","amount":11.66,"category":"Restaurants","memo":""},
{"date":"2015-09-14","month":"Sep","item":"ALBERTSONS, AZ","amount":8.68,"category":"Grocery stores","memo":""},
{"date":"2015-09-16","month":"Sep","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-09-18","month":"Sep","item":"FRYS FUEL, AZ","amount":24.47,"category":"Gas stations","memo":""},
{"date":"2015-09-18","month":"Sep","item":"CHOMPIES RESTAURANT DELI, AZ","amount":14.9,"category":"Restaurants","memo":""},
{"date":"2015-09-18","month":"Sep","item":"CHOMPIES RESTAURANT DELI, AZ","amount":19.04,"category":"Restaurants","memo":""},
{"date":"2015-09-26","month":"Sep","item":"MCDONALD'S, OR","amount":8.33,"category":"Restaurants","memo":""},
{"date":"2015-09-28","month":"Sep","item":"FRYS FUEL, AZ","amount":20,"category":"Gas stations","memo":""},
{"date":"2015-10-01","month":"Oct","item":"AT&T*BILL PAYMENT, TX","amount":128.63,"category":"Utilities","memo":""},
{"date":"2015-10-01","month":"Oct","item":"BURGER KING, AZ","amount":16.01,"category":"Restaurants","memo":"Ummmm"},
{"date":"2015-10-04","month":"Oct","item":"SAFEWAY STORE, AZ","amount":21.65,"category":"Grocery stores","memo":"Medicine pickup"},
{"date":"2015-10-04","month":"Oct","item":"COX*PHOENIX COMM SERV, AZ","amount":49.99,"category":"Utilities","memo":""},
{"date":"2015-10-04","month":"Oct","item":"ZOYO FROZEN YOGURT, AZ","amount":15.73,"category":"Restaurants","memo":"Yummy!"},
{"date":"2015-10-04","month":"Oct","item":"COSTCO WHOLESALE PHOENIX AZ","amount":482.33,"category":"Grocery stores","memo":""},
{"date":"2015-10-04","month":"Oct","item":"COSTCO GAS PHOENIX AZ","amount":17.2,"category":"Gas stations","memo":""},
{"date":"2015-10-05","month":"Oct","item":"COSTCO WHOLESALE PHOENIX AZ","amount":22.37,"category":"Grocery stores","memo":""},
{"date":"2015-10-07","month":"Oct","item":"FRYS-FOOD-DRG, AZ","amount":4.02,"category":"Grocery stores","memo":""},
{"date":"2015-10-08","month":"Oct","item":"City Phx Water Payment PPD","amount":81.72,"category":"Utilities","memo":""},
{"date":"2015-10-11","month":"Oct","item":"COSTCO GAS PHOENIX AZ","amount":18.19,"category":"Gas stations","memo":""},
{"date":"2015-10-13","month":"Oct","item":"FRYS-FOOD-DRG, AZ","amount":3.56,"category":"Grocery stores","memo":""},
{"date":"2015-10-16","month":"Oct","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-10-17","month":"Oct","item":"FRYS-FOOD-DRG, AZ","amount":4.57,"category":"Grocery stores","memo":""},
{"date":"2015-10-17","month":"Oct","item":"FRYS FUEL, AZ","amount":20,"category":"Gas stations","memo":""},
{"date":"2015-10-23","month":"Oct","item":"FRYS-FOOD-DRG, AZ","amount":101.24,"category":"Grocery stores","memo":""},
{"date":"2015-10-24","month":"Oct","item":"FRYS-FOOD-DRG, AZ","amount":14.83,"category":"Grocery stores","memo":""},
{"date":"2015-10-24","month":"Oct","item":"COSTCO WHOLESALE PHOENIX AZ","amount":5.4,"category":"Grocery stores","memo":""},
{"date":"2015-10-24","month":"Oct","item":"COSTCO WHOLESALE PHOENIX AZ","amount":24.96,"category":"Grocery stores","memo":""},
{"date":"2015-10-24","month":"Oct","item":"COSTCO GAS PHOENIX AZ","amount":13.58,"category":"Gas stations","memo":""},
{"date":"2015-10-29","month":"Oct","item":"COSTCO WHOLESALE PHOENIX AZ","amount":3.78,"category":"Grocery stores","memo":""},
{"date":"2015-10-29","month":"Oct","item":"COSTCO WHOLESALE PHOENIX AZ","amount":79.99,"category":"Grocery stores","memo":""},
{"date":"2015-10-29","month":"Oct","item":"COSTCO WHOLESALE PHOENIX AZ","amount":455.91,"category":"Grocery stores","memo":""},
{"date":"2015-10-31","month":"Oct","item":"COSTCO GAS PHOENIX AZ","amount":19.11,"category":"Gas stations","memo":""},
{"date":"2015-11-01","month":"Nov","item":"City Phx Water Payment PPD","amount":78.29,"category":"Utilities","memo":""},
{"date":"2015-11-01","month":"Nov","item":"AT&T*BILL PAYMENT, TX","amount":128.85,"category":"Utilities","memo":""},
{"date":"2015-11-03","month":"Nov","item":"COX*PHOENIX COMM SERV, AZ","amount":49.99,"category":"Utilities","memo":""},
{"date":"2015-11-05","month":"Nov","item":"FRYS FUEL, AZ","amount":22.55,"category":"Gas stations","memo":""},
{"date":"2015-11-07","month":"Nov","item":"ASIANA MARKET, AZ","amount":35.65,"category":"Grocery stores","memo":""},
{"date":"2015-11-07","month":"Nov","item":"COSTCO WHOLESALE PHOENIX AZ","amount":11.48,"category":"Grocery stores","memo":""},
{"date":"2015-11-07","month":"Nov","item":"COSTCO GAS PHOENIX AZ","amount":20.37,"category":"Gas stations","memo":""},
{"date":"2015-11-08","month":"Nov","item":"COSTCO WHOLESALE PHOENIX AZ","amount":6.59,"category":"Grocery stores","memo":""},
{"date":"2015-11-12","month":"Nov","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-11-16","month":"Nov","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-11-16","month":"Nov","item":"COSTCO GAS PHOENIX AZ","amount":25.19,"category":"Gas stations","memo":""},
{"date":"2015-11-20","month":"Nov","item":"FRYS-FOOD-DRG, AZ","amount":1.71,"category":"Grocery stores","memo":""},
{"date":"2015-11-21","month":"Nov","item":"COSTCO WHOLESALE PHOENIX AZ","amount":131.47,"category":"Grocery stores","memo":""},
{"date":"2015-11-21","month":"Nov","item":"COSTCO GAS PHOENIX AZ","amount":20.38,"category":"Gas stations","memo":""},
{"date":"2015-11-23","month":"Nov","item":"ALBERTSONS, AZ","amount":139.27,"category":"Grocery stores","memo":""},
{"date":"2015-11-25","month":"Nov","item":"FRYS FUEL, AZ","amount":19.62,"category":"Gas stations","memo":""},
{"date":"2015-11-26","month":"Nov","item":"FRYS-FOOD-DRG, AZ","amount":7.57,"category":"Grocery stores","memo":""},
{"date":"2015-11-28","month":"Nov","item":"MCDONALD'S, OR","amount":7.46,"category":"Restaurants","memo":""},
{"date":"2015-11-29","month":"Nov","item":"FRYS-FOOD-DRG, AZ","amount":69.99,"category":"Grocery stores","memo":""},
{"date":"2015-12-01","month":"Dec","item":"City Phx Water Payment PPD","amount":66.01,"category":"Utilities","memo":""},
{"date":"2015-12-01","month":"Dec","item":"AT&T*BILL PAYMENT, TX","amount":128.53,"category":"Utilities","memo":""},
{"date":"2015-12-06","month":"Dec","item":"HODORI RESTAURANT, AZ","amount":37.26,"category":"Restaurants","memo":""},
{"date":"2015-12-07","month":"Dec","item":"COSTCO GAS PHOENIX AZ","amount":20.38,"category":"Gas stations","memo":""},
{"date":"2015-12-10","month":"Dec","item":"FRYS-FOOD-DRG, AZ","amount":19.78,"category":"Grocery stores","memo":""},
{"date":"2015-12-10","month":"Dec","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-12-10","month":"Dec","item":"COSTCO WHOLESALE PHOENIX AZ","amount":50.59,"category":"Grocery stores","memo":""},
{"date":"2015-12-14","month":"Dec","item":"FRYS-FOOD-DRG, AZ","amount":6.49,"category":"Grocery stores","memo":""},
{"date":"2015-12-16","month":"Dec","item":"NETFLIX.COM, CA","amount":9.74,"category":"Utilities","memo":""},
{"date":"2015-12-16","month":"Dec","item":"COX*PHOENIX COMM SERV, AZ","amount":124.98,"category":"Utilities","memo":""},
{"date":"2015-12-17","month":"Dec","item":"CHICK-FIL-A, AZ","amount":15.65,"category":"Restaurants","memo":""},
{"date":"2015-12-18","month":"Dec","item":"FRYS FUEL, AZ","amount":20.68,"category":"Gas stations","memo":""},
{"date":"2015-12-19","month":"Dec","item":"ASIANA MARKET, AZ","amount":2.98,"category":"Grocery stores","memo":""},
{"date":"2015-12-19","month":"Dec","item":"HODORI RESTAURANT, AZ","amount":31.24,"category":"Restaurants","memo":""},
{"date":"2015-12-19","month":"Dec","item":"COSTCO GAS PHOENIX AZ","amount":17.25,"category":"Gas stations","memo":""},
{"date":"2015-12-20","month":"Dec","item":"MARIGOLD MAISON, AZ","amount":27.74,"category":"Restaurants","memo":""},
{"date":"2015-12-22","month":"Dec","item":"FRYS FUEL, AZ","amount":24.35,"category":"Gas stations","memo":""},
{"date":"2015-12-24","month":"Dec","item":"COSTCO WHOLESALE PHOENIX AZ","amount":1.62,"category":"Grocery stores","memo":"Hot dog purchase"},
{"date":"2015-12-24","month":"Dec","item":"COSTCO WHOLESALE PHOENIX AZ","amount":94.21,"category":"Grocery stores","memo":""},
{"date":"2015-12-26","month":"Dec","item":"COSTCO WHOLESALE PHOENIX AZ","amount":13.18,"category":"Grocery stores","memo":""},
{"date":"2015-12-29","month":"Dec","item":"COSTCO WHOLESALE PHOENIX AZ","amount":72.38,"category":"Grocery stores","memo":""},
{"date":"2015-12-29","month":"Dec","item":"COSTCO GAS PHOENIX AZ","amount":11.07,"category":"Gas stations","memo":""},
{"date":"2015-12-30","month":"Dec","item":"FRYS FUEL, AZ","amount":24.14,"category":"Gas stations","memo":""},
      ]);
      // {date:'2015-03-15' ,month: "Jan",item:"Albertson", amount:30.67, category: "Grocery", memo:"wanted banana"},
      // {date:'2015-01-21', month: "Jan",item:"iPhone", amount:649.99, category: "Electronic", memo:"I don't remember when I bought this.  I was so drunk last night...."},
      // {date:'2015-02-06', month: "Feb",item:"Safeway", amount:55.34, category: "Grocery", memo:"Ice cream was on sale"},
      // {date:'2015-2-15', month: "Feb",item:"Apple bees", amount:72.99, category: "Restaurant", memo:"Wasn't good"},
      // {date:'2015-03-26', month: "Mar",item:"Fry's food", amount:83.34, category: "Grocery", memo:"Save $10 yeah!"},
      // {date:'2015-03-15', month: "Mar",item:"Office depot", amount:72.99, category: "Office", memo:"Expensive!!"},
    });
};
